pipeline:
  publish:
    image: plugins/docker
    when:
      branch: master
    settings:
      tags: ${CI_COMMIT_SHA:0:8}
#       username:
#         from_secret: local_docker_registry_user
#       password:
#         from_secret: local_docker_registry_pass
#       repo:
#         from_secret: local_docker_repo
#       registry:
#         from_secret: local_docker_registry
